apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.group }}-{{ .Values.cluster }}-operators
  namespace: gitops-{{ .Values.group }}
spec:
  generators:
    - git:
        repoURL: 'https://8200gitlab[REDACTED]/redbull/gitops-day2-prod/sigs/{{ .Values.group }}.git'
        revision: main
        directories:
          - path: "mces/{{ .Values.mce }}/{{ .Values.cluster }}/*"
    {{- if eq .Values.cluster "in-cluster" }}
    - git:
        repoURL: 'https://8200gitlab[REDACTED]/redbull/gitops-day2-prod/sigs/{{ .Values.group }}.git'
        revision: main
        directories:
          - path: "mces/in-cluster-defaults/charts/*"
    {{- end }}
  template:
    metadata:
      name: '{{ .Values.group }}-{{ .Values.cluster }}-{{ "{{" }}path.basename{{ "}}" }}'
    spec:
      project: '{{ .Values.group }}'
      sources:
        - repoURL: 'https://8200gitlab[REDACTED]/redbull/gitops-day2-prod/argocd-day2-platform.git'
          targetRevision: main
          path: deploy
          helm:
            ignoreMissingValueFiles: true
            values: |
              group: '{{ .Values.group }}'
              mce: {{ .Values.mce }}
              cluster: {{ .Values.cluster }}
              operator: {{ "{{" }}path.basename{{ "}}" }}
            valueFiles:
              - '$values/operators/{{ "{{" }}path.basename{{ "}}" }}/{{ "{{" }}path.basename{{ "}}" }}.yaml'
              {{- if eq .Values.cluster "in-cluster" }}
              - '$values/mces/in-cluster-defaults/charts/{{ "{{" }}path.basename{{ "}}" }}/{{ "{{" }}path.basename{{ "}}" }}.yaml'
              {{- end }}
              - '$values/mces/{{ .Values.mce }}/{{ .Values.cluster }}/{{ "{{" }}path.basename{{ "}}" }}/{{ "{{" }}path.basename{{ "}}" }}.yaml'
        - ref: values
          repoURL: 'https://8200gitlab[REDACTED]/redbull/gitops-day2-prod/sigs/{{ .Values.group }}.git'
          targetRevision: main
      destination:
        name: in-cluster
        namespace: gitops-{{ .Values.group }}
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - CreateNamespace=true